# Generated by Django 5.2 on 2025-04-07 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_customuser_movie_watched'),
    ]

    operations = [
        migrations.AddField(
            model_name='animemovie',
            name='watchedCount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
