# Generated by Django 5.2 on 2025-04-07 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_animemovie_watchedcount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animemovie',
            old_name='watchedCount',
            new_name='watched_count',
        ),
    ]
