# Generated by Django 5.2 on 2025-04-07 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_watchedcount_animemovie_watched_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animemovie',
            name='watched_count',
        ),
    ]
