# Generated by Django 5.2 on 2025-04-07 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_animemovie_watched_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Drama', 'Drama'), ('Comedy', 'Comedy'), ('Adventure', 'Adventure'), ('Romance', 'Romance'), ('Horror', 'Horror'), ('Fantasy', 'Fantasy'), ('Action', 'Action'), ('Sci-Fi', 'Sci-Fi'), ('Thriller', 'Thriller'), ('Mystery', 'Mystery'), ('Sports', 'Sports'), ('Supernatural', 'Supernatural'), ('Slice of Life', 'Slice of Life'), ('Gourmet', 'Gourmet'), ('Avant-garde', 'Avant-garde')], max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='animemovie',
            name='genres',
            field=models.ManyToManyField(blank=True, related_name='anime_movies', to='main.genre'),
        ),
    ]
