# Generated by Django 5.2 on 2025-04-07 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_genre_animemovie_genres'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animemovie',
            name='genres',
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
        migrations.AddField(
            model_name='animemovie',
            name='genres',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
